repos:
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
  - id: isort
    additional_dependencies: [toml]

- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.761
  hooks:
    - id: mypy
      exclude: ^(tests)|(tools)/.*

- repo: https://github.com/PyCQA/pylint
  # TODO: Update to v2.5.0 when available (for pyproject.toml)
  rev: 06fa7751aee84fe7f4b5be4354484067a8acb729
  hooks:
    - id: pylint
      # We disable import-error since this is run outside poetry venv
      args: [--errors-only, --disable=import-error, --disable=unsubscriptable-object]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
