repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [--profile=black]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    exclude: ^tests/.*

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a4
  hooks:
  - id: pylint
    # We disable import-error since this is run outside poetry venv.
    # We also disable no-value-for-parameter:
    # https://github.com/PyCQA/pylint/issues/259
    args: [--errors-only, --disable=import-error, --disable=unsubscriptable-object, --disable=no-value-for-parameter]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^README.md$
  - id: check-yaml
  - id: check-added-large-files
    exclude: ^fetchmesh/mocks/.*
