name: CI

on: push

jobs:
  # Run unit tests on Linux
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install project
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest
      
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # Build package and verify that it installs
  # correctly on different OSes
  pkg_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build package
        run: |
          pip install poetry
          poetry build

      - name: Install package
        run: pip install "$(ls dist/*.whl)"

      - name: Test package
        run: fetchmesh --help
