name: CI

on: push

jobs:
  # Run unit tests on Linux
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install project
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest

      - name: Run doctets
        run: poetry run make -C docs/ doctest

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # Build package and verify that it installs
  # correctly on different OSes.
  # We do not test on macOS since it is too "expensive" on GH actions
  # (1 macOS minute = 10 Linux minutes)
  pkg_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Build package
        run: |
          pip install poetry
          poetry build

      - name: Install package
        run: pip install "$(ls dist/*.whl)"

      - name: Test package
        run: fetchmesh --help
