name: Documentation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install LaTeX
        run: |
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk

      - name: Install project
        run: |
          pip install poetry
          poetry install

      - name: Build documentation
        run: |
          poetry run make -C docs/ latexpdf
          find docs/_build/latex/ -type f -not -name '*.pdf' -exec rm '{}' \;

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/_build/latex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
